#!/bin/sh
# 
# Copyright (C) 2009  The University of Texas at Austin.
# 
# This file is part of Hydra: A wireless multihop testbed.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 

# All this strange PYTHONPATH manipulation is required to run our
# tests using our just built shared library and swig-generated python
# code prior to installation.

# build tree == src tree unless you're doing a VPATH build.  
# If you don't know what a VPATH build is, you're not doing one.  Relax...

prefix=/home/testbed/hydra-0.4/gr
exec_prefix=${prefix}

# Where to look in the build tree for our shared library
libbld=/home/testbed/hydra-0.4/gr-hydra/src/swig/rf
libbldphy=/home/testbed/hydra-0.4/gr-hydra/src/swig/phy
# Where to look in the src tree for swig generated python code
libsrc=/home/testbed/hydra-0.4/gr-hydra/src/swig/rf
libsrc=$libsrc:/home/testbed/hydra-0.4/gr-hydra/src/swig/phy
# Where to look in the src tree for hand written python code
py=/home/testbed/hydra-0.4/gr-hydra/src/python/rf
py=$py:/home/testbed/hydra-0.4/gr-hydra/src/python/core

# Where to look for installed GNU Radio python modules
# FIXME this is wrong on a distcheck.  We really need to ask gnuradio-core
# where it put its python files.
installed_pythondir=${prefix}/lib/python2.6/site-packages
installed_pyexecdir=${exec_prefix}/lib/python2.6/site-packages

PYTHONPATH="$libbld:$libbld/.libs:$libbldphy:$libbldphy/.libs:$libsrc:$py:$installed_pythondir:$installed_pyexecdir:$PYTHONPATH"
#PYTHONPATH="$libbld:$libbld/.libs:$libsrc:$py:$installed_pythondir:$installed_pyexecdir"

export PYTHONPATH

#
# This is the simple part...
# Run everything that matches qa_*.py and return the final result.
#

ok=yes
for file in ./qa_*.py
do
  if ! $file
  then
    ok=no
  fi  
done

if [ $ok = yes ]
then
  exit 0
else
  exit 1
fi
